// Present-day form catalogue. Only explicitly cited dimensions are documentary;
// other metre values are proportional modelling estimates, NOT a measured survey.
// Evidence and current-state distinctions: docs/CITY_GATES_REFERENCES.md.
const three = (spacing, middle, side, spring) => [
  { x: -spacing, width: side, spring },
  { x: 0, width: middle, spring },
  { x: spacing, width: side, spring },
];
const estimate = '现状形制核对；未取得测绘图的尺寸为比例估算';
export const GATE_SPECS = {
  '中华门': { widthM: 118.5, depthM: 52.6, innerExtentM: 128, wallH: 20.45, wallDeckM: 18.65, joinDeckH: 10.75, bays: 4, tower: false, road: false,
    accuracy: '公开记载118.5×128米、总高20.45米；内部分段与细部为估算',
    note: '四道纵列券门、三重内瓮城；主台6+7、东西马道各7个藏兵洞；现存城台无木构城楼' },
  '通济门': { widthM: 64, depthM: 18, wallH: 0, bays: 0, road: true, tower: false,
    urn: null, accuracy: '门址示意；原城门已拆除', note: '原三重内瓮城已拆，现状只标门址，不重建完整瓮城' },
  '光华门': { widthM: 52, depthM: 20, wallH: 0, bays: 0, road: true, tower: false, remnant: .9,
    urn: null, accuracy: '遗址残段示意；边界和残高未测绘', note: '正阳门；保留低矮遗迹表达，不复建城楼与瓮城' },
  '中山门': { widthM: 50, depthM: 18, wallH: 13.5, bays: 3, tower: false, road: true, dress: 'stone',
    openings: three(13, 8, 8, 5), accuracy: estimate, note: '现状三券并列、无城楼；迎榇大道穿门而过' },
  '太平门': { widthM: 54, depthM: 16, wallH: 12.5, bays: 3, tower: false, road: true,
    openings: three(14, 9, 8, 4.6), accuracy: estimate, note: '2014年形成的三孔通道；平顶城台，不搭建旧制城楼' },
  '解放门': { widthM: 32, depthM: 15, wallH: 13, bays: 1, tower: false, road: false, facade: 'render', crenels: false,
    openings: [{ x: 0, width: 10, spring: 3.6, rise: 3.4 }], accuracy: estimate,
    note: '1954年在台城段开辟的单孔通道；平顶城台连接台城步道' },
  '玄武门': { widthM: 42, depthM: 15, wallH: 11, bays: 3, tower: true, road: false, dress: 'stone',
    openings: three(11, 6.5, 5.2, 3.6), towerSpec: { width: 25, depth: 8, body: 4, roof: 3.3, tiers: 2, bays: 7, color: '#607865' },
    accuracy: estimate, note: '三孔券门，上有1980年代重建城楼；通向玄武湖的步行入口' },
  '神策门': { widthM: 36, depthM: 18, wallH: 14, bays: 1, tower: true, road: false, urn: 'outer',
    openings: [{ x: 0, width: 4.8, spring: 3.4 }],
    towerSpec: { width: 18, depth: 8, body: 5.2, roof: 3.6, tiers: 2, bays: 3, color: '#626655' },
    court: { width: 58, depth: 38, height: 9, entry: 14, side: 1, thickness: 6, span: 4.5 },
    accuracy: estimate, note: '单券门、清代歇山门楼与外瓮城；主门和瓮门错位，园区步行通行' },
  '金川门': { widthM: 48, depthM: 14, wallH: 0, bays: 0, tower: false, road: true,
    urn: null, accuracy: '门址示意；原城门已拆除', note: '原金川门已拆，现状仅标门址，不虚构瓮城和城楼' },
  '仪凤门': { widthM: 56, depthM: 22, wallH: 14.5, bays: 3, tower: true, road: false,
    openings: [{ x: -15, width: 6, spring: 4.6 }, { x: 0, width: 13, spring: 3.1 }, { x: 15, width: 6, spring: 4.6 }],
    towerSpec: { width: 28, depth: 12, body: 7, roof: 5, tiers: 2, bays: 7, color: '#62775b' },
    accuracy: '施工报道主券13×9.6米、侧券6×7.6米；城台与楼体尺寸估算', note: '2006年复建现状：三孔券门、重檐城楼，区别于历史单孔门' },
  '挹江门': { widthM: 54, depthM: 18, wallH: 13.5, bays: 3, tower: true, road: true,
    lightingProfile: 'yijiang-reference',
    openings: three(14, 8, 7, 4.6), towerSpec: { width: 29, depth: 9.5, body: 6.5, roof: 3.8, tiers: 2, bays: 7, color: '#696a58' },
    accuracy: estimate, note: '三孔券门及城楼；门台沿中山北路横跨道路' },
  '钟阜门': { widthM: 46, depthM: 14, wallH: 0, bays: 0, tower: false, road: true,
    accuracy: '门址示意；原城门已拆除', note: '原钟阜门已拆除，仅保留门址标记' },
  '清凉门': { widthM: 28, depthM: 16.34, wallH: 13.8, bays: 1, tower: false, road: false, urn: null,
    openings: [{ x: 0, width: 5.87, spring: 5.865, rise: 2.935 }],
    accuracy: '文献券洞5.87米宽、8.8米高、16.34米长；其余尺寸估算',
    note: '单券古门现存，旧内瓮城已拆；保留券洞，不重建完整内瓮城' },
  '汉中门': { widthM: 58, depthM: 36, wallH: 10, joinDeckH: 10, bays: 1, tower: false, road: false, profile: 'hanzhong', crenels: false,
    siteWidthM: 112, innerExtentM: 99, urn: 'ruin', court: null,
    openings: [{ x: 0, width: 5.6, spring: 3.7 }],
    accuracy: '现存石城门瓮城轮廓示意；尺寸与残高估算',
    note: '石城门（汉西门）现存瓮城遗址；与近代汉中门区分，保留围合残墙和登城台阶' },
  '水西门': { widthM: 54, depthM: 16, wallH: 0, bays: 0, tower: false, road: true, urn: null,
    accuracy: '门址示意；原城门已拆除', note: '原三山门已拆除，仅标门址；不搭建推测的城楼、内瓮城' },
};
